name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      # 빌드 전략 매핑을 우회하고nice_nano_v2 보드를 직접 지정하여 빌드합니다.
      board_list: '["nice_nano_v2"]'
