name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test Firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 올바른 ZMK 공식 빌드 액션 주소(zmk-build-action) 사용
      - name: Build nice_nano_v2
        uses: zmkfirmware/zmk-build-action@v2
        with:
          board: nice_nano_v2
